use mavenmovies;
show tables;

select* from customer;

-- Here are the questions:
-- Use Mavenmovies database
-- 1. Display the first 10 records from the customer table.
select* from customer order by customer_id limit 10;
-- 2. Display the first 3 records from the customer table whose first name starts with ‘b’.
select* from customer where first_name like 'b%' order by customer_id limit 3;

select* from customer;

-- 3. Display the names of the first 5 movies which are rated as ‘G’.
select title from film where rating = 'G' limit 5;

-- 4. Find all customers whose first name starts with "a".

SELECT *
FROM customer
WHERE first_name LIKE 'A%';

-- 5. Find all customers whose first name ends with "a".
SELECT *
FROM customer
WHERE first_name LIKE '%a';

-- 6. Display the list of the first 4 cities which start and end with ‘a’.
SELECT CITY FROM CITY WHERE city like 'a%a' limit 4;

-- 7. Find all customers whose first name has "NI" in any position.
select* from customer where first_name like '%NI%';

-- 8. Find all customers whose first name has "r" in the second position.
SELECT * FROM customer WHERE first_name LIKE '_r%';

-- 9. Find all customers whose first name starts with "a" and is at least 5 characters in length.
SELECT * FROM customer WHERE first_name LIKE 'A____%';

-- 10. Find all customers whose first name starts with "a" and ends with "o".
SELECT * FROM customer WHERE first_name LIKE 'A%o';

-- 11. List all details of actors.
SELECT * FROM actor;

-- 12. List all customer information from the database.
SELECT* FROM CUSTOMER;

-- 13. List different countries.
SELECT DISTINCT country FROM country ORDER BY country;

-- 14. Display all active customers.
select* from customer where active = 1;

-- 15. List all rental IDs for the customer with ID 1.
select* from rental;

-- 16. Display all the films whose rental duration is greater than 5.
SELECT * FROM film WHERE rental_duration > 5;

-- 17. List the total number of films whose replacement cost is greater than $15 and less than $20.
select* from film;
select count(*) as total_films from film where replacement_cost >15 and replacement_cost<20;

-- 18. Find the number of films whose rental rate is less than $1.
select count(rental_rate) from film where rental_rate <1;


-- 19. List the total number of rentals for each customer, ordered by the total number of rentals in descending order.
select* from rental;
select* from rental order by customer_id;

select customer_id, count(customer_id) from rental 
group by customer_id 
order by customer_id desc;

-- 20. Find the average rental duration for each film rating, but only include categories where the average duration is more than 5 days.
select rating, avg(rental_duration) as Average_rental_duration from film group by rating having Average_rental_duration >5;

-- 21. Retrieve the top 10 customers who have made the highest total payments.
select* from payment;
SELECT customer_id, SUM(amount) AS total_payment
FROM payment
GROUP BY customer_id
ORDER BY total_payment DESC
LIMIT 10;

-- 22. List the films that have a rental rate between $2.00 and $4.00, ordered by title alphabetically.
select* from film;
select * from film where rental_rate between 2 and 3 order by title asc;  

-- 23. Find the total number of active customers, grouped by store.
select store_id, count(store_id) as Active_customers from customer where active = 1  group by store_id;

-- 24. List the number of films with each rating, ordered by the rating alphabetically.
select rating, count(rating) from film group by rating order by rating asc;


-- 25. Calculate the total revenue generated by each staff and only include staff with revenue over $50,000.
select* from film;
-- 26. Retrieve the films that are longer than 120 minutes and order them by length in descending order.
SELECT* FROM FILM;
SELECT* from film where length > 120 order by length desc;

-- 27. List the total number of films in each rating category where the rental duration is exactly 7 days.
select rating, count(rating) as Films_count from film where rental_duration = 7 group by rating;

-- 28. Find the total number of films with a replacement cost greater than $20, grouped by rating.
select rating, count(rating) as film_count from film where replacement_cost>20 group by rating;

-- 29. List the average rental rate of films in each language, and order the results by the average rate in ascending order.
select* from film;
select language_id, avg(rental_rate)
from film
group by language_id;

-- 30. Calculate the total number of rentals made in the year 2006 and group them by month.
select* from rental;
select month(rental_date) as Month, count(rental_id) as Number_of_Rentals
from rental where year(rental_date) = 2006
group by month;

-- 31. Find the number of films that have a special feature of 'Behind the Scenes' and are less than 100 minutes long.
select* from film;
select count(film_id) as Number_Of_Films from film where special_features like '%Behind the Scenes%' and length < 100;

-- 32. Retrieve the films where the length is not equal to 90 minutes, grouped by length, and ordered by the number of films in descending order.
select length, count(*) as film_count from film where length != 90 group by length order by length desc;

-- 33. List the number of customers who have a staff ID of 1 and have made more than 10 rentals.
select customer_id, count(*) as Customer_count from rental where staff_id = 1 group by customer_id having Customer_count > 10;

-- 34. Find the total payment amount for each day in 2007, but only include days where the total payment exceeds $100.
SELECT DATE(payment_date) AS day, SUM(amount) AS total_amount
FROM payment
WHERE YEAR(payment_date) = 2007
GROUP BY day
HAVING total_amount > 100
ORDER BY day;

-- 35. Retrieve the films with a replacement cost that is not divisible by 5.
SELECT *
FROM film
WHERE MOD(replacement_cost, 5) <> 0;

-- 36. List the number of customers who signed up on each date in 2006, ordered by the date in ascending order.
SELECT DATE(create_date) AS signup_date, COUNT(*) AS signups
FROM customer
WHERE YEAR(create_date) = 2006
GROUP BY signup_date
ORDER BY signup_date ASC;

-- 37. Calculate the total number of payments made in each quarter of 2007.
SELECT* FROM payment;
SELECT QUARTER(payment_date) AS quarter, COUNT(*) AS total_payments
FROM payment
WHERE YEAR(payment_date) = 2007
GROUP BY quarter
ORDER BY quarter;

-- 38. Find the films where the rental rate is either $0.99, $2.99, or $4.99, and order them by rental rate in ascending order.
use mavenmovies;
SELECT *
FROM film
WHERE rental_rate IN (0.99, 2.99, 4.99)
ORDER BY rental_rate ASC, title ASC;